NVIDIA/doca-sosreport

debian/changelog, debian/control, debian/install, debian/rules, setup.py, sos-mlx-cloud-verification.conf, sos.spec, sos/__init__.py
add sos-mlx-cloud-verification.conf to repo and debian build
=> Move debian build to doca-sosreport

requirements.txt
updating because of blackduck check
=> Update sphinx version

sos.spec
adding sos to obsolete
adding sos-mlx-cloud-verification.conf to rpm build
=> Fix rpm conflict with sos

sos.spec
=> Update sos spec

sos/report/plugins/openvswitch.py
=> Add doca openvswitch support

sos/report/plugins/mlx5_core.py
=> Add mlx5_core pluginx

sos/report/plugins/openvswitch.py
on deb doca ovs called doca-openvswitch-switch
=> Fix openvswitch on deb systems

sos/report/plugins/hbn.py
HBN stand for a host based networking
=> Add HBN plugin

sos/report/plugins/mellanox_firmware.py
remove subvendor from lspci command to include all the devices using mcra command to validate that devices are supported
some devices are not matching  0000:08: format, this fix is resolving the format issue
=> fix mellanox_firmware device mapping

sos/report/plugins/openvswitch.py
=> Add meter commands

sos/report/plugins/openvswitch.py
=> [openvswitch] Add mirror list command

sos-mlx-cloud-verification.conf, sos/report/plugins/rdma.py
=> Fix mlx cfg

sos/report/plugins/openvswitch.py
=> [openvswitch] Add missing OpenFlow13 for meter commands

.github/workflows/build-deb.yaml, debian/install, debian/rules, setup.py, sos.spec
add sos-nvidia.conf to installation
=> fix default-config

sos/report/plugins/doca.py
=> Add doca plugin

sos/report/plugins/rdma.py
Also, use mlnx-iproute2 when available
---
=> Fix rdma plugin package

sos/report/plugins/devlink_health.py, sos/report/plugins/libreswan.py
=> devlink health and stats for xfrm state

.github/workflows/build-rpm.yaml, sos/collector/sosnode.py, sos/report/plugins/coredump.py
=> fix python syntax issues with old python versions

.github/workflows/build-rpm.yaml, sos/collector/sosnode.py, sos/report/plugins/coredump.py
=> Fix python issuse

.github/workflows/release.yaml, Dockerfile
=> fix docker build issue

sos.spec
=> fix sos package conflict by obsoleting sos

.github/workflows/release.yaml
=> add release with latest for main branch

Dockerfile, debian/install, debian/rules, setup.py, sos-nvdebug.conf, sos.spec
adding minimal set of plugins that want to run as part of nvdebug
---
=> add sos-nvdebug.conf file

requirements.txt
=> fix: set packaging package requirement for minimal version

sos-nvdebug.conf, sos-nvidia.conf
=> imp: add all-logs flag to nvidia config files

sos/report/plugins/snap_service.py
=> [snap_service] Adds snap_service plugin

sos/report/plugins/doca.py
=> doca: fix sos_logs path
